//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlazasREST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.People = new HashSet<Person>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public byte type { get; set; }
        public string docnumber { get; set; }
        public string name { get; set; }
        public string phone1 { get; set; }
        public string phone1ext { get; set; }
        public string phone2 { get; set; }
        public string phone3 { get; set; }
        public string fax { get; set; }
        public string faxext { get; set; }
        public string pobox { get; set; }
        public string password { get; set; }
        public bool enable { get; set; }
        public Nullable<int> questionid { get; set; }
        public string answer { get; set; }
        public bool passwordreset { get; set; }
        public int parentid { get; set; }
        public int failed { get; set; }
        public bool bModify { get; set; }
        public string reason { get; set; }
        public bool isnew { get; set; }
        public Nullable<long> ItemWF { get; set; }
        public Nullable<long> ItemModifyWF { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<System.DateTime> lastmodifydate { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
    }
}
