//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlazasREST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int id { get; set; }
        public int customerid { get; set; }
        public Nullable<byte> titleid { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public Nullable<byte> gender { get; set; }
        public string name2 { get; set; }
        public string lastname1 { get; set; }
        public string lastname2 { get; set; }
        public string maidenname { get; set; }
        public Nullable<byte> maritalstatus { get; set; }
        public string occupation { get; set; }
        public string nationality { get; set; }
        public Nullable<int> careerid { get; set; }
        public string birthplace { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
