//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlazasREST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<System.DateTime> lastinventory { get; set; }
        public bool enabled { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public Nullable<System.DateTime> openingAt { get; set; }
        public Nullable<System.DateTime> closingAt { get; set; }
        public Nullable<System.DateTime> sunOpeningAt { get; set; }
        public Nullable<System.DateTime> sunClosingAt { get; set; }
    }
}
